## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("C:\\Users\\Blaine\\Documents\\College\\Bootcamp\\World_Weather_Analysis\\Weather_Database\\WeatherPy_Database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Ushuaia,AR,-54.8000,-68.3000,40.658,93,100,6.17,light intensity drizzle
1,1,Atuona,PF,-9.8000,-139.0333,78.854,78,26,7.61,scattered clouds
2,2,Ferme-Neuve,CA,46.7001,-75.4493,41.288,59,49,1.97,scattered clouds
3,3,Butaritari,KI,3.0707,172.7902,79.628,80,76,2.59,light rain
4,4,Jamestown,US,42.0970,-79.2353,47.948,41,100,1.34,overcast clouds

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
1,1,Atuona,PF,-9.8000,-139.0333,78.854,78,26,7.61,scattered clouds
3,3,Butaritari,KI,3.0707,172.7902,79.628,80,76,2.59,light rain
6,6,Puerto Ayora,EC,-0.7393,-90.3518,80.564,91,100,1.34,overcast clouds
11,11,Lakota,CI,5.8528,-5.6883,87.944,57,87,1.95,overcast clouds
13,13,Mount Isa,AU,-20.7333,139.5000,83.966,26,12,2.57,light rain
16,16,Rikitea,PF,-23.1203,-134.9692,78.908,73,2,8.90,clear sky
24,24,Saldanha,ZA,-33.0117,17.9442,84.254,53,0,4.74,clear sky
26,26,Olinda,BR,-8.0089,-34.8553,85.730,62,40,3.09,scattered clouds
32,32,Castro,BR,-24.7911,-50.0119,77.054,56,59,3.00,moderate rain
35,35,Komsomolskiy,UZ,40.4272,71.7189,77.720,33,88,1.03,overcast clouds

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.isnull().sum()

City_ID                0
City                   0
Country                3
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Current Description    0
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.dropna()

In [7]:
clean_df.isnull().sum()

City_ID                0
City                   0
Country                0
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Current Description    0
dtype: int64

In [8]:
clean_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
1,1,Atuona,PF,-9.8000,-139.0333,78.854,78,26,7.61,scattered clouds
3,3,Butaritari,KI,3.0707,172.7902,79.628,80,76,2.59,light rain
6,6,Puerto Ayora,EC,-0.7393,-90.3518,80.564,91,100,1.34,overcast clouds
11,11,Lakota,CI,5.8528,-5.6883,87.944,57,87,1.95,overcast clouds
13,13,Mount Isa,AU,-20.7333,139.5000,83.966,26,12,2.57,light rain
...,...,...,...,...,...,...,...,...,...,...
660,660,Mount Darwin,ZW,-16.7725,31.5838,77.090,56,64,1.35,broken clouds
662,662,Alyangula,AU,-13.8483,136.4192,78.674,94,40,0.00,scattered clouds
666,666,Nisia Floresta,BR,-6.0911,-35.2086,88.178,52,89,4.30,light rain
667,667,Muncar,ID,-8.4333,114.3333,75.866,83,79,0.36,broken clouds
672,672,Kaohsiung,TW,22.6163,120.3133,79.034,70,20,2.06,few clouds

In [40]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[['City', 'Country', 'Lat', 'Lng', 'Max Temp', 'Humidity', 'Cloudiness', 'Wind Speed', 'Current Description']].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Hotel Name
1,Atuona,PF,-9.8000,-139.0333,78.854,78,26,7.61,scattered clouds,
3,Butaritari,KI,3.0707,172.7902,79.628,80,76,2.59,light rain,
6,Puerto Ayora,EC,-0.7393,-90.3518,80.564,91,100,1.34,overcast clouds,
11,Lakota,CI,5.8528,-5.6883,87.944,57,87,1.95,overcast clouds,
13,Mount Isa,AU,-20.7333,139.5000,83.966,26,12,2.57,light rain,
16,Rikitea,PF,-23.1203,-134.9692,78.908,73,2,8.90,clear sky,
24,Saldanha,ZA,-33.0117,17.9442,84.254,53,0,4.74,clear sky,
26,Olinda,BR,-8.0089,-34.8553,85.730,62,40,3.09,scattered clouds,
32,Castro,BR,-24.7911,-50.0119,77.054,56,59,3.00,moderate rain,
35,Komsomolskiy,UZ,40.4272,71.7189,77.720,33,88,1.03,overcast clouds,

In [41]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 24141,
    "type": "lodging",
    "key": g_key,
    "location": "42.65, -73.75"}

# Use base URL to search for hotels.
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
# Make request and get the JSON data from the search.
hotels = requests.get(base_url, params=params).json()

hotels

{'html_attributions': [],
 'next_page_token': 'Aap_uEDRzp5MwcUhDY_0kukYZh6wMuJQX-iBOsyb-m7IMD2xQL6KgFFF8SkeDQGhRtOBgBdhRcr5D5K_N371eiXSP1uCyn02daJ3Gm72rvaEWuwvtugaL-oTV-eXdvQ6mmCiPqeqO7JVOT5Z7xY3q6_GbTZlP3lWNetC7_I5rBWBl8tWVN24davnMRPS2uSSiaeblmTKrOuKXfWkfzIz0eU2AHpW1LQ-N1_on-Lp2WCynTTrMNpRQ5m3X_UVYd6N1gDb75MIaAf1E5KGuzAisn_I6DufSyzHmZr5u8jDvtw9gn7rvSZXdzh8cX6grDpuLCN3reHKpQ0DFMQT57jtXwcCCvkgjMeN1pPNeYoX4A5wJQ0aDz1eEuvBGUyw5w1wlCKbwS5sDkGOjOj1_TSMDMFWogJ-k3zDP4sDM30j4sGUhybGKiSM4DvdtPDT',
 'results': [{'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 42.6506469, 'lng': -73.75312339999999},
    'viewport': {'northeast': {'lat': 42.65205538029149,
      'lng': -73.75212566970848},
     'southwest': {'lat': 42.64935741970849, 'lng': -73.7548236302915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hilton Albany',
   'photos': [{'height': 4032,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/114534858979559033885">Jerry Rogich</a>'],
     'photo_reference': 'Aap_uEAQiQd_5DSsVfKsJ-CThTKIEumKUrAoM5I_mTl0EanXXfAd_zBBQR5o5fGYcYtkY6-ZOsrtVXksPH81GmnfrOrk18ouEKZiAzpvtzBLejY0TlbPvb7Yl50mMz_sHLcNgJdc13IiP0nAfjUVquvFVDw1chSjX1Fw0A07SLN0l2iD6Bfc',
     'width': 3024}],
   'place_id': 'ChIJKWgGHCQK3okRgxizNC_gd4U',
   'plus_code': {'compound_code': 'M62W+7Q Albany, NY, USA',
    'global_code': '87J8M62W+7Q'},
   'rating': 3.6,
   'reference': 'ChIJKWgGHCQK3okRgxizNC_gd4U',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 2072,
   'vicinity': '40 Lodge Street, Albany'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 42.6534971, 'lng': -73.75154789999999},
    'viewport': {'northeast': {'lat': 42.65478333029149,
      'lng': -73.75011621970849},
     'southwest': {'lat': 42.65208536970849, 'lng': -73.7528141802915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hampton Inn & Suites Albany-Downtown',
   'photos': [{'height': 913,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/111650991760080029985">Hampton Inn &amp; Suites Albany-Downtown</a>'],
     'photo_reference': 'Aap_uECAB4KiFhW9AaxC80980n155666Y7Undh3HEFNWnI5-7XBdz-6kv6_0ANaM9r2rt1jVy0sNvXqOK_TILSD12mjisnyF18aWWUphOajwm00OcTsmK8pCfcvp__hdfwk0vr_J08aV_sZcXuOU2KKz-2-t0wteRJ46Ls-9jHj40AFugJJs',
     'width': 1280}],
   'place_id': 'ChIJSfaaOiYK3okRfad-IU_ylKw',
   'plus_code': {'compound_code': 'M63X+99 Albany, NY, USA',
    'global_code': '87J8M63X+99'},
   'rating': 4.1,
   'reference': 'ChIJSfaaOiYK3okRfad-IU_ylKw',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 1036,
   'vicinity': '25 Chapel Street, Albany'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 42.6454798, 'lng': -73.7504088},
    'viewport': {'northeast': {'lat': 42.64695018029149,
      'lng': -73.74877336970849},
     'southwest': {'lat': 42.64425221970849, 'lng': -73.75147133029151}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Holiday Inn Express Albany - Downtown, an IHG Hotel',
   'photos': [{'height': 1068,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/103718494850107588219">Holiday Inn Express Albany - Downtown, an IHG Hotel</a>'],
     'photo_reference': 'Aap_uEAS61JgYZjdcXqF81Nn4FR5eVGits53FxHOvyY49-u-A3dPnj2GoOzIAtK2z5pIRJC6t5ntj7oxgt-ALqOxpmXmPzNkHPHhzIxzoKAs7hHNSORAwLvC9HtAcjIwTC9eW1B-ITTNJrByL7QFLk9N6rQby0L7cRlDpQIj_f069_ZTpruk',
     'width': 1900}],
   'place_id': 'ChIJL5zANSAK3okRPegJyCn07pI',
   'plus_code': {'compound_code': 'J6WX+5R Albany, NY, USA',
    'global_code': '87J8J6WX+5R'},
   'rating': 4.1,
   'reference': 'ChIJL5zANSAK3okRPegJyCn07pI',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 690,
   'vicinity': '300 Broadway, Albany'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 42.6523365, 'lng': -73.7761732},
    'viewport': {'northeast': {'lat': 42.6535400802915,
      'lng': -73.77493756970851},
     'southwest': {'lat': 42.6508421197085, 'lng': -73.77763553029152}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hilton Garden Inn Albany Medical Center',
   'photos': [{'height': 1038,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/111123195987860795364">Hilton Garden Inn Albany Medical Center</a>'],
     'photo_reference': 'Aap_uEBQWa20V-PLkAm9_NH0I6rb9P9nsXBaOk7CDJ8ObycOVw8_cRNez0sUDaGHI0mpDVkOOIAItaD6bnUdDlaaTgottznAV3Jz5gtAqenTJSxA3wUjsdgPgCz3ibX8HAANUzUHFcKMYM_GVAge8b-JTjDkrVDfZgKWlkF6-ZC85HDpUid1',
     'width': 2048}],
   'place_id': 'ChIJKy_yWkEK3okRTST_YWO21QE',
   'plus_code': {'compound_code': 'M62F+WG Albany, NY, USA',
    'global_code': '87J8M62F+WG'},
   'rating': 4.3,
   'reference': 'ChIJKy_yWkEK3okRTST_YWO21QE',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 693,
   'vicinity': '62 New Scotland Avenue, Albany'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 42.68054890000001,
     'lng': -73.78358349999999},
    'viewport': {'northeast': {'lat': 42.6819097802915,
      'lng': -73.78222376970848},
     'southwest': {'lat': 42.6792118197085, 'lng': -73.7849217302915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Ramada Plaza by Wyndham Albany',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 400,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/107024876999517019966">Ramada Plaza by Wyndham Albany</a>'],
     'photo_reference': 'Aap_uEDMxAcoNBAw-_fjLeBdl7Irw25zJjLEHgNoQ1k5j3L7X144XaOXj9effCL_RxSz69GE4rLb-xNGkhbQrnQU38ClZIlwKYWyluYwvzSS4oRFDZTlPiGRdVZncKvaPtd0aZIzeMF1kvspLNQPOiNlYcczlyVBO2GffPlbX8tyD_evIyDV',
     'width': 600}],
   'place_id': 'ChIJC6CszaQL3okRrqdAMxjFB1o',
   'plus_code': {'compound_code': 'M6J8+6H Albany, NY, USA',
    'global_code': '87J8M6J8+6H'},
   'rating': 2.4,
   'reference': 'ChIJC6CszaQL3okRrqdAMxjFB1o',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 1298,
   'vicinity': '3 Watervliet Avenue Extension, Albany'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 42.672161, 'lng': -73.7511413},
    'viewport': {'northeast': {'lat': 42.6736126802915,
      'lng': -73.75000676970849},
     'southwest': {'lat': 42.6709147197085, 'lng': -73.75270473029151}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Red Carpet Inn Northern Blvd. Albany, NY',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 719,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/107613139966170038675">Red Carpet Inn Northern Blvd. Albany, NY</a>'],
     'photo_reference': 'Aap_uECiYyFUSNE-dZH1sHiQesQ4kzPb8qasCDrc11c5fYM_Gc12AhFJ-c9uTA4wm4_DSg0ALJYnncwY6kYwLLmrv0SD84hcuqkA0LGaq5BUgwc0-MbJyyMe7vxytgNJQWTbTqUGgWbB3VtpfJ0ZzLyLQ8swUgPsAmwZFIJAyig9OL51tMg-',
     'width': 1200}],
   'place_id': 'ChIJL22xbtcL3okR_IDt60NTnf0',
   'plus_code': {'compound_code': 'M6CX+VG Albany, NY, USA',
    'global_code': '87J8M6CX+VG'},
   'rating': 3.2,
   'reference': 'ChIJL22xbtcL3okR_IDt60NTnf0',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 295,
   'vicinity': '500 Northern Boulevard, Albany'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 42.65694010000001,
     'lng': -73.76573549999999},
    'viewport': {'northeast': {'lat': 42.6582233802915,
      'lng': -73.76445886970849},
     'southwest': {'lat': 42.6555254197085, 'lng': -73.7671568302915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Morgan State House Inn',
   'opening_hours': {'open_now': False},
   'photos': [{'height': 1800,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/116827858303080099681">Morgan State House Inn</a>'],
     'photo_reference': 'Aap_uEBpYGG1oJZv7iAW6qf7z-Am7vLANIPTdbE2LXXZqRwjR4tDQyHSG5N9CqZEnXdZQp-7QxlmQ6Yhi8bprlLVQkn95mdDrMeFawlCVD9K6dlGkkl-AfQbunXZrqzDwzlFcZftAj5XpBTkA2631OyDTmzoIbc6EeS8CV9ibNy2lRQ2JW-v',
     'width': 2880}],
   'place_id': 'ChIJR9tBTDcK3okR2X-7lz38cVw',
   'plus_code': {'compound_code': 'M64M+QP Albany, NY, USA',
    'global_code': '87J8M64M+QP'},
   'rating': 4.6,
   'reference': 'ChIJR9tBTDcK3okR2X-7lz38cVw',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 115,
   'vicinity': '393 State Street, Albany'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 42.64625100000001, 'lng': -73.772409},
    'viewport': {'northeast': {'lat': 42.6476791302915,
      'lng': -73.77085616970848},
     'southwest': {'lat': 42.6449811697085, 'lng': -73.7735541302915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'TownePlace Suites by Marriott Albany Downtown/Medical Center',
   'photos': [{'height': 1366,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/115968308554601824004">TownePlace Suites by Marriott Albany Downtown/Medical Center</a>'],
     'photo_reference': 'Aap_uED-8_i5Ey632jh7ng956om-uryZR-WlX2gtKh3Z4XMqXf8IHAaRo9R4TGizi3P6RG9LbH11LwZQD9OKPMDL9Nez63vdYIfLaVrgtNLJuhs5-OhK76QcXgesuz9AAxil-ZIYlVU98xd8iYMbloSrQQqJgYV0tEfLDeyND8OVUHER9Cnf',
     'width': 2048}],
   'place_id': 'ChIJdzuvwWoK3okRahCD-RVk2zg',
   'plus_code': {'compound_code': 'J6WH+G2 Albany, NY, USA',
    'global_code': '87J8J6WH+G2'},
   'rating': 4.2,
   'reference': 'ChIJdzuvwWoK3okRahCD-RVk2zg',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 412,
   'vicinity': '22 Holland Avenue, Albany'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 42.6791635, 'lng': -73.7827185},
    'viewport': {'northeast': {'lat': 42.6806668302915,
      'lng': -73.78165966970849},
     'southwest': {'lat': 42.6779688697085, 'lng': -73.78435763029151}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Motel 6 Albany, NY',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1907,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/103947272161323415151">Motel 6 Albany, NY</a>'],
     'photo_reference': 'Aap_uEB7cX2cgkB40VozWgNMmTBUI3gZ52pADqtpVwx1z3OBagNZx2VBYHQ8Q9YcyXzVVtOEyU0dtNsSRVHmZO1eTLJoftw1Xqr3zr1vNSr45UzRJLib9AKfd_wDg2JhjgmGtBgdlLS1k1qJmeTfMHgbkWCrtV9JGjbgZqFSN__mjhCGLO-S',
     'width': 2879}],
   'place_id': 'ChIJ88vVnsYI3okRo00kUtKq_CQ',
   'plus_code': {'compound_code': 'M6H8+MW Albany, NY, USA',
    'global_code': '87J8M6H8+MW'},
   'rating': 3,
   'reference': 'ChIJ88vVnsYI3okRo00kUtKq_CQ',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 1175,
   'vicinity': '100 Watervliet Avenue, Albany'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 42.632346, 'lng': -73.70176699999999},
    'viewport': {'northeast': {'lat': 42.6342798, 'lng': -73.70055716970847},
     'southwest': {'lat': 42.6301782, 'lng': -73.7032551302915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Holiday Inn Express & Suites East Greenbush(Albany-Skyline), an IHG Hotel',
   'photos': [{'height': 3000,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/104006022187463878753">Owned St</a>'],
     'photo_reference': 'Aap_uEByP0OgkPbpjQVJdwpVayN4x_fiQ7h8w6Bb-v4LmH4LO_TFtrIvOiSd2-PCGYNm2kKXKHtrK5RvqjH7-5Ox7GX09NpAFA2lsUVm82RTqoQIq8t9ndHQLtmiAp7zACi991LhnD_vj7P2CeYao_ZSiEAQmlC2qzpBQwBpAqWKYbsG2Z7z',
     'width': 4000}],
   'place_id': 'ChIJkeITo8wJ3okRGmrpMoNTogE',
   'plus_code': {'compound_code': 'J7JX+W7 Rensselaer, NY, USA',
    'global_code': '87J8J7JX+W7'},
   'rating': 4,
   'reference': 'ChIJkeITo8wJ3okRGmrpMoNTogE',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 374,
   'vicinity': '8 Empire Drive, Rensselaer'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 42.622228, 'lng': -73.778481},
    'viewport': {'northeast': {'lat': 42.6237731802915,
      'lng': -73.7769034197085},
     'southwest': {'lat': 42.6210752197085, 'lng': -73.77960138029151}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Comfort Inn Glenmont - Albany South',
   'photos': [{'height': 5504,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/111452139386596809796">Comfort Inn Glenmont - Albany South</a>'],
     'photo_reference': 'Aap_uEB1TLfzKTkzxp4LQji-sbe36w6hJT2SrP2k1lHCH-piswCrPcocse5b87lKY1PJ_lkTap_Yhfs0kJgvMSUjX_b5xyuT4aGlG0K_2odWMTEh4qGiM_3hxYC5V1jVK1G0GHl_3w9rAcDLd0NkNFSGb3u-j1cqrtBpYebRHcK2l92hWL_H',
     'width': 8256}],
   'place_id': 'ChIJ4Tr4dNvh3YkR3t-VH5cTc28',
   'plus_code': {'compound_code': 'J6CC+VJ Glenmont, NY, USA',
    'global_code': '87J8J6CC+VJ'},
   'rating': 3.9,
   'reference': 'ChIJ4Tr4dNvh3YkR3t-VH5cTc28',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 406,
   'vicinity': '37 Route 9W, Glenmont'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 42.6590462, 'lng': -73.7835343},
    'viewport': {'northeast': {'lat': 42.6604230802915,
      'lng': -73.78223121970849},
     'southwest': {'lat': 42.6577251197085, 'lng': -73.7849291802915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Luxury Studio in the Old Plumbers Union Building',
   'photos': [{'height': 4160,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/106442656581071151059">Manuel Velecela</a>'],
     'photo_reference': 'Aap_uEAbKpfK4eAqwtzVKYVzo397eJszL8LTZrGtl_t4zdqla2x7-kHC659bR4Y0DlHVKEwRQ6hGMmeHVcCRkthZnTMlbBYEzEZRS-7726QjrAwd9C5Ubbl6wDw-xB5vwiviODqUkmrbkoHQlVJ6b9qYtrc8iYrmR953cXtsfKmAjFTkO67z',
     'width': 2080}],
   'place_id': 'ChIJ__8YBFAK3okRx_qBQTtYSsY',
   'plus_code': {'compound_code': 'M658+JH Albany, NY, USA',
    'global_code': '87J8M658+JH'},
   'rating': 5,
   'reference': 'ChIJ__8YBFAK3okRx_qBQTtYSsY',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 2,
   'vicinity': '328 Ontario Street, Albany'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 42.6201186, 'lng': -73.7824613},
    'viewport': {'northeast': {'lat': 42.6215211802915,
      'lng': -73.78105961970849},
     'southwest': {'lat': 42.6188232197085, 'lng': -73.7837575802915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Quality Inn & Suites Glenmont - Albany South',
   'photos': [{'height': 1920,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/107568795897307719588">Quality Inn &amp; Suites Glenmont - Albany South</a>'],
     'photo_reference': 'Aap_uEBPlUTWIbcbtsbFBIsgKs4uVCll8v6kJTRRt0M_9hKjZI_Kq5_4CiZKvGIYDAybBWZxkeKuYiHyvEuD-csekDOUKpj7aHU98W1SmieOQWOta1p_PyuCPjdN8KssGfzah4FfCJlX3qy1ReaY-KHbFep3Kf0lE7pBIOfFzEPStMl-E4_l',
     'width': 2880}],
   'place_id': 'ChIJvZZVUMXh3YkRLSgEoMYE2sA',
   'plus_code': {'compound_code': 'J6C9+22 Glenmont, NY, USA',
    'global_code': '87J8J6C9+22'},
   'rating': 3.5,
   'reference': 'ChIJvZZVUMXh3YkRLSgEoMYE2sA',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 220,
   'vicinity': '15 Frontage Road, Glenmont'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 42.67893, 'lng': -73.78570959999999},
    'viewport': {'northeast': {'lat': 42.68019898029151,
      'lng': -73.78427086970851},
     'southwest': {'lat': 42.67750101970851, 'lng': -73.78696883029151}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png',
   'icon_background_color': '#7B9EB0',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/generic_pinlet',
   'name': 'Unite Here',
   'place_id': 'ChIJ9yytgqUL3okR6rWwRfirvcg',
   'plus_code': {'compound_code': 'M6H7+HP Albany, NY, USA',
    'global_code': '87J8M6H7+HP'},
   'reference': 'ChIJ9yytgqUL3okR6rWwRfirvcg',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'vicinity': '890 3rd Street, Albany'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 42.654514, 'lng': -73.761222},
    'viewport': {'northeast': {'lat': 42.65573793029149,
      'lng': -73.76000731970849},
     'southwest': {'lat': 42.65303996970849, 'lng': -73.76270528029151}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'State Street Mansion B & B',
   'photos': [{'height': 3024,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/109865883714498258621">David Bardi</a>'],
     'photo_reference': 'Aap_uEB8hzmlF3iCylS9M83Q99-1aVZ1xHoskeBdd6Ki8HQfB-9x6rffv-pBuYMA2GRFrbYVaChle833GJvAr779FjNZhboZX73zImqhR4Zi1bmi-9A5dfq0wpFDoMgfUsa7fJpbDS8yvSn4WDuW9hC1MlbztGv7szR0RxpdKTUtzqdNu1o',
     'width': 4032}],
   'place_id': 'ChIJFXpKlDoK3okRIJVFnbCuE5k',
   'plus_code': {'compound_code': 'M63Q+RG Albany, NY, USA',
    'global_code': '87J8M63Q+RG'},
   'rating': 3,
   'reference': 'ChIJFXpKlDoK3okRIJVFnbCuE5k',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 4,
   'vicinity': '281 State Street, Albany'},
  {'business_status': 'OPERATIONAL',

In [42]:
len(hotels["results"])

20

In [46]:
# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]

    # 6d. Make request and retrieve the JSON data from the search.
    params["location"] = f"{lat},{lng}"

    # 6e. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
# 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
try:
    hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
except (IndexError):
    print("Hotel not found... skipping.")

In [47]:
hotel_df.head(10)

,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Hotel Name
1,Atuona,PF,-9.8000,-139.0333,78.854,78,26,7.61,scattered clouds,Villa Enata
3,Butaritari,KI,3.0707,172.7902,79.628,80,76,2.59,light rain,Isles Sunset Lodge
6,Puerto Ayora,EC,-0.7393,-90.3518,80.564,91,100,1.34,overcast clouds,Finch Bay Galapagos Hotel
11,Lakota,CI,5.8528,-5.6883,87.944,57,87,1.95,overcast clouds,Aziz bah divers
13,Mount Isa,AU,-20.7333,139.5000,83.966,26,12,2.57,light rain,ibis Styles Mt Isa Verona
16,Rikitea,PF,-23.1203,-134.9692,78.908,73,2,8.90,clear sky,People ThankYou
24,Saldanha,ZA,-33.0117,17.9442,84.254,53,0,4.74,clear sky,Club Mykonos Resort
26,Olinda,BR,-8.0089,-34.8553,85.730,62,40,3.09,scattered clouds,Recife Plaza Hotel
32,Castro,BR,-24.7911,-50.0119,77.054,56,59,3.00,moderate rain,L'acqua Motel Express
35,Komsomolskiy,UZ,40.4272,71.7189,77.720,33,88,1.03,overcast clouds,Grand Osiyo Plaza

In [48]:
import numpy as np

In [49]:
hotel_df['Hotel Name'].replace('', np.nan, inplace=True)

In [50]:
hotel_df['Hotel Name'].replace('0', np.nan, inplace=True)

In [51]:
hotel_df.isnull().sum()

City                    0
Country                 0
Lat                     0
Lng                     0
Max Temp                0
Humidity                0
Cloudiness              0
Wind Speed              0
Current Description     0
Hotel Name             64
dtype: int64

In [52]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.dropna()

In [53]:
clean_hotel_df.head(10)

,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Hotel Name
1,Atuona,PF,-9.8000,-139.0333,78.854,78,26,7.61,scattered clouds,Villa Enata
3,Butaritari,KI,3.0707,172.7902,79.628,80,76,2.59,light rain,Isles Sunset Lodge
6,Puerto Ayora,EC,-0.7393,-90.3518,80.564,91,100,1.34,overcast clouds,Finch Bay Galapagos Hotel
11,Lakota,CI,5.8528,-5.6883,87.944,57,87,1.95,overcast clouds,Aziz bah divers
13,Mount Isa,AU,-20.7333,139.5000,83.966,26,12,2.57,light rain,ibis Styles Mt Isa Verona
16,Rikitea,PF,-23.1203,-134.9692,78.908,73,2,8.90,clear sky,People ThankYou
24,Saldanha,ZA,-33.0117,17.9442,84.254,53,0,4.74,clear sky,Club Mykonos Resort
26,Olinda,BR,-8.0089,-34.8553,85.730,62,40,3.09,scattered clouds,Recife Plaza Hotel
32,Castro,BR,-24.7911,-50.0119,77.054,56,59,3.00,moderate rain,L'acqua Motel Express
35,Komsomolskiy,UZ,40.4272,71.7189,77.720,33,88,1.03,overcast clouds,Grand Osiyo Plaza

In [54]:
# 8a. Create the output File (CSV)
output_data_file = "C:\\Users\\Blaine\\Documents\\College\\Bootcamp\\World_Weather_Analysis\\Weather_Database\\WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [55]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [56]:
# 11a. Add a marker layer for each city to the map. 
# Add a heatmap of temperature for the vacation spots.
max_temp = clean_hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))